### ISSUE TITLE
一个想法，可否从抖音的手机APP

### ISSUE THREAD

**Issue by a1640727878** [LFMJUN/douyin_rtmp#1]
最近折腾时发现，抖音手机app直播条件特别低，而用直播伴侣要千粉或者满足一堆乱七八糟的条件，如果从手机app处能抓到直播，也变向降低直播门槛

**Comment by LFMJUN** [comment]
手机抓包网上有很多现成的办法，而且已经有比较成熟的方案进行抓包，暂时不考虑做手机抓包
